--CategoryExpenses
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (1,-1,'Abonament za Internet',false,0);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (2,-1,'Abonament za telefon',false,1);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (3,-1,'AGD',false,2);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (4,-1,'Alkohol',false,3);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (5,-1,'Artykuły spożywcze',false,4);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (6,-1,'Aukcje Allegro.pl',false,5);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (7,-1,'Club/Dyskoteka',false,8);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (8,-1,'Darowizna',false,9);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (9,-1,'Dług',false,10);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (10,-1,'Doładowanie telefonu',false,11);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (11,-1,'Dom',false,12);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (12,-1,'Energia',false,13);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (13,-1,'Faktura',false,14);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (14,-1,'Fitness',false,15);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (15,-1,'Fryzjer',false,16);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (16,-1,'Fundusz emerytalny',false,17);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (17,-1,'Fundusz remontowy',false,18);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (18,-1,'Hosting+domena',false,20);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (19,-1,'Inne',false,22);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (20,-1,'Kino',false,23);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (21,-1,'Kosmetyki',false,25);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (22,-1,'Książki',false,26);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (23,-1,'Księgarnia internetowa',false,27);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (24,-1,'Kurs tańca',false,29);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (25,-1,'Leki',false,31);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (26,-1,'Lodowisko',false,32);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (27,-1,'Meble',false,35);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (28,-1,'Mikropłatności w Internecie',false,36);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (29,-1,'Nauka angielskiego',false,38);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (30,-1,'Odzież',false,40);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (31,-1,'Opłata licencyjna',false,41);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (32,-1,'Opłata za prowadzenie rachunku',false,42);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (33,-1,'Opłaty za parkowanie',false,43);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (34,-1,'Podatek',false,46);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (35,-1,'Podatek cit',false,47);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (36,-1,'Podatek inny',false,48);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (37,-1,'Podatek PIT',false,49);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (38,-1,'Podatek rozliczenie roczne',false,50);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (39,-1,'Podatek VAT',false,51);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (40,-1,'Polisa na życie',false,52);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (41,-1,'Polisa z funduszem',false,53);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (42,-1,'Prenumerata',false,54);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (43,-1,'Prezenty',false,55);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (44,-1,'Rata',false,57);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (45,-1,'Remont',false,58);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (46,-1,'Rozrywka',false,60);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (47,-1,'RTV',false,61);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (48,-1,'Samochód',false,62);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (49,-1,'Siłownia',false,63);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (50,-1,'Sklep internetowy',false,64);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (51,-1,'Spłata długu',false,65);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (52,-1,'Środki czystości',false,66);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (53,-1,'Tankowanie',false,67);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (54,-1,'Telefon komórkowy',false,68);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (55,-1,'Ubezpieczenie',false,70);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (56,-1,'Ubezpieczenie samochodu',false,71);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (57,-1,'Ubezpieczenie towaru',false,72);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (58,-1,'Wycieczka',false,75);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (59,-1,'Za usługę',false,76);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (60,-1,'Zakup samochodu',false,77);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (61,-1,'Zaliczka',false,78);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (62,-1,'Zasilenie rachunku',false,79);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (63,-1,'Zwrot pożyczki',false,82);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (64,-1,'Przelew Pensji z firmowego do RoR',false,56);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (65,-1,'Pizza',false,45);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (66,-1,'PIT-5L',false,44);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (67,-1,'Łóżko',false,33);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (68,-1,'MultiSport',false,37);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (69,-1,'AZS Tańce',false,6);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (70,-1,'VAT 7',false,73);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (71,-1,'Tidal',false,69);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (72,-1,'Obuwie',false,39);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (73,-1,'ZUS',false,81);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (74,-1,'Rower',false,59);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (75,-1,'Księgoway',false,28);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (76,-1,'KomunikacjaMiejska',false,24);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (77,-1,'Mandat',false,34);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (78,-1,'Lekarz',false,30);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (79,-1,'Hotel',false,21);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (80,-1,'Biurowe',false,7);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (81,-1,'Zdrowie',false,80);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (82,-1,'Wakacje',false,74);
INSERT INTO public."CategoryExpenses"("Id","CategoryGroupId","Description","IsDeleted","Weight") VALUES (83,-1,'Higiena',false,19);
