// <auto-generated />
using System;
using ManagementFinanceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ManagementFinanceApp.Migrations
{
  [DbContext(typeof(ManagementFinanceAppDbContext))]
  partial class ManagementFinanceAppDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
        .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
        .HasAnnotation("Relational:MaxIdentifierLength", 63);

      modelBuilder.Entity("ManagementFinanceApp.Entities.Blog", b =>
      {
        b.Property<int>("BlogId")
          .ValueGeneratedOnAdd();

        b.Property<string>("Url");

        b.HasKey("BlogId");

        b.ToTable("Blogs");
      });

      modelBuilder.Entity("ManagementFinanceApp.Entities.CategoryGroup", b =>
      {
        b.Property<int>("Id")
          .ValueGeneratedOnAdd();

        b.Property<int>("CategoryType");

        b.Property<bool>("IsDeleted");

        b.Property<string>("Name")
          .IsRequired();

        b.HasKey("Id");

        b.ToTable("CategoryGroups");
      });

      modelBuilder.Entity("ManagementFinanceApp.Entities.Expense", b =>
      {
        b.Property<int>("Id")
          .ValueGeneratedOnAdd();

        b.Property<string>("Attachment");

        b.Property<string>("Comment");

        b.Property<DateTime>("Date");

        b.Property<double>("HowMuch");

        b.Property<bool>("StandingOrder");

        b.HasKey("Id");

        b.ToTable("Expenses");
      });

      modelBuilder.Entity("ManagementFinanceApp.Entities.Post", b =>
      {
        b.Property<int>("PostId")
          .ValueGeneratedOnAdd();

        b.Property<int>("BlogId");

        b.Property<string>("Content");

        b.Property<string>("Title");

        b.HasKey("PostId");

        b.HasIndex("BlogId");

        b.ToTable("Posts");
      });

      // modelBuilder.Entity("ManagementFinanceApp.Entities.User", b =>
      //     {
      //         b.Property<int>("Id")
      //             .ValueGeneratedOnAdd();

      //         b.Property<string>("Address");

      //         b.Property<string>("Email")
      //             .IsRequired()
      //             .HasMaxLength(50);

      //         b.Property<string>("FirstName")
      //             .IsRequired()
      //             .HasMaxLength(30);

      //         b.Property<bool>("IsDelete");

      //         b.Property<string>("LastName")
      //             .HasMaxLength(40);

      //         b.Property<string>("Nick")
      //             .HasMaxLength(20);

      //         b.Property<string>("Phone");

      //         b.HasKey("Id");

      //         b.ToTable("Users");
      //     });

      modelBuilder.Entity("ManagementFinanceApp.Entities.Post", b =>
      {
        b.HasOne("ManagementFinanceApp.Entities.Blog", "Blog")
          .WithMany("Posts")
          .HasForeignKey("BlogId")
          .OnDelete(DeleteBehavior.Cascade);
      });
#pragma warning restore 612, 618
    }
  }
}